spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: 1234567

  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS

  jackson:
    default-property-inclusion: non_null

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher #pra funcionar o swagger

jwt:
  secret: 95bdf312-e9ca-4818-a94c-dc9c95f2cb5a
  expiration: 999999
